# Copyright 2024 Advanced Micro Devices
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: IREE Test Suite
on:
  # TODO(scotttodd): run on schedule (nightly), and/or on pushes to `main`
  pull_request:
    paths:
      - "iree_tests/**"
  workflow_dispatch:

jobs:
  linux_x86_64:
    name: Linux (x86_64)
    runs-on: ubuntu-latest
    env:
      VENV_DIR: ${{ github.workspace }}/.venv
    steps:
      - name: "Checking out repository"
        uses: actions/checkout@v4
      - name: "Setting up Python"
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # TODO(scotttodd): swap this with workflow artifact downloads
      # TODO(scotttodd): make this configurable with workflow inputs
      - name: "Installing IREE nightly release Python packages"
        run: |
          python3 -m venv ${VENV_DIR}
          source ${VENV_DIR}/bin/activate
          python3 -m pip install \
            --find-links https://iree.dev/pip-release-links.html \
            --upgrade \
            iree-compiler \
            iree-runtime

      # TODO(scotttodd): replace everything below here with pytest calls

      - name: "Print baseline test results"
        run: |
          echo "Baseline compile failures:"
          cat iree_tests/onnx/node/compile_failures.txt
          echo "Baseline compile successes:"
          cat iree_tests/onnx/node/compile_successes.txt
          echo "Baseline run failures:"
          cat iree_tests/onnx/node/run_failures.txt
          echo "Baseline run successes:"
          cat iree_tests/onnx/node/run_successes.txt

      - name: "Test compilation"
        run: |
          source ${VENV_DIR}/bin/activate
          python iree_tests/compile_tests.py
      - name: "Test running"
        run: |
          source ${VENV_DIR}/bin/activate
          python iree_tests/run_tests.py

      - name: "Print test results"
        run: |
          echo "Tested compile failures:"
          cat iree_tests/onnx/node/compile_failures.txt
          echo "Tested compile successes:"
          cat iree_tests/onnx/node/compile_successes.txt
          echo "Tested run failures:"
          cat iree_tests/onnx/node/run_failures.txt
          echo "Tested run successes:"
          cat iree_tests/onnx/node/run_successes.txt
